[project]
dependencies = []
name = "charfreq-tools"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[tool.black]
line-length = 100
target-version = ['py313']

[tool.pylint.'MESSAGES CONTROL']
disable = ["invalid-name", "missing-docstring"]
